<?php

namespace AppBundle\Repository;

/**
 * orders_detailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class orders_detailRepository extends \Doctrine\ORM\EntityRepository
{
}
