<?php

namespace AppBundle\Repository;

/**
 * PORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PORepository extends \Doctrine\ORM\EntityRepository
{
}
