<?php

namespace AppBundle\Repository;

/**
 * product_invetoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class product_invetoryRepository extends \Doctrine\ORM\EntityRepository
{
}
