<?php

namespace AppBundle\Repository;

/**
 * quotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class quotationRepository extends \Doctrine\ORM\EntityRepository
{
}
