<?php

namespace AppBundle\Repository;

/**
 * suppliers_bankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suppliers_bankRepository extends \Doctrine\ORM\EntityRepository
{
}
