<?php

namespace AppBundle\Repository;

/**
 * suppliers_quotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suppliers_quotationRepository extends \Doctrine\ORM\EntityRepository
{
}
