<?php

namespace AppBundle\Repository;

/**
 * userROLERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userROLERepository extends \Doctrine\ORM\EntityRepository
{
}
